
--CREAR TABLA PLATAFORMA




--CREAR TABLA MIS_JUEGOS
CREATE TABLE MIS_JUEGOS(  
    ID_JUEGO INT NOT NULL,
    NOMBRE VARCHAR(50),
    GENERO VARCHAR(50),
    NOTA INT
);
--DEFINIR LA CLAVE PRIMARIA
ALTER TABLE MIS_JUEGOS ADD CONSTRAINT PK_JUEGOS PRIMARY KEY (ID_JUEGO);

--INSERTAR DATOS
INSERT INTO MIS_JUEGOS (ID_JUEGO,NOMBRE,GENERO,NOTA) VALUES (10,'Half life 3','Shooter',10);
INSERT INTO MIS_JUEGOS (ID_JUEGO,NOMBRE,GENERO,NOTA) VALUES (20,'Minecraft','SandBox',9);
INSERT INTO MIS_JUEGOS (ID_JUEGO,NOMBRE,GENERO,NOTA) VALUES (30,'Superman 64','Aventura',2);

--SELECCIONAR INFORMACION MEDIANTE UNA CONDICION
SELECT NOMBRE,GENERO
FROM MIS_JUEGOS WHERE NOTA  >=9;

--ACTUALIZAR
UPDATE MIS_JUEGOS SET NOTA = 1 WHERE ID_JUEGO = 30;

--BORRAR
DELETE FROM MIS_JUEGOS WHERE NOMBRE = 'Superman 64';