CREATE TABLE AUTOR(
    RUT VARCHAR(12) NOT NULL,
    NOMBRE_AUTOR VARCHAR(50) NOT NULL,
    CONSTRAINT RUT_PK PRIMARY KEY (RUT)
);


CREATE TABLE LIBROS(
    ISBN VARCHAR(10) NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    GENERO VARCHAR(20) NOT NULL,
    AUTOR_RUT VARCHAR(12) NOT NULL,
    CONSTRAINT ISBN_PK PRIMARY KEY (ISBN),
    CONSTRAINT RUT_AUTOR_PK FOREIGN KEY (AUTOR_RUT) REFERENCES AUTOR(RUT)
);




--CRUD AUTOR
INSERT INTO AUTOR(RUT,NOMBRE_AUTOR) 
VALUES('2-9','DIEGO PALDAÑA');


SELECT NOMBRE_AUTOR
FROM AUTOR;

UPDATE AUTOR
SET NOMBRE_AUTOR= 'DIEGO SALDAÑA',
WHERE RUT='2-9';

DELETE FROM NOMBRE_AUTOR
WHERE NOMBRE_AUTOR='DIEGO SALDAÑA';



--CRUD LIBROS
INSERT INTO LIBROS(ISBN,TITULO,GENERO) VALUES(1,'Papelucho','Aventuras','2-9');
INSERT INTO LIBROS(ISBN,TITULO,GENERO) VALUES(2,'Papelucho En la Clinica','Aventuras','2-9');

SELECT TITULO,GENERO
FROM LIBROS;

UPDATE LIBROS
SET TITULO ='Papelucho en vaciones'
WHERE ISBN =1;

DELETE FROM  LIBROS
WHERE TITULO = 'Papelucho En la Clinica';
