CREATE DATABASE ESTA
GO
USE ESTA
GO

CREATE TABLE ESTACION(
	CODIGO_ESTACION VARCHAR(20) NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL,
	CONTACTO VARCHAR(12) NOT NULL,
	DIRECCION VARCHAR(70) NOT NULL,
	KMS VARCHAR(20) NOT NULL,
	CONSTRAINT COD_EST_PK PRIMARY KEY (CODIGO_ESTACION)
);

CREATE TABLE  TELEFONO(
	COD_TELEFONO VARCHAR(12) NOT NULL,
	NUM_TELEFONO INT,
	CONSTRAINT COD_TEL_PK PRIMARY KEY (COD_TELEFONO)
);

CREATE TABLE PISTA(
	COD_PISTA VARCHAR(20) NOT NULL,
	DIFICULTAD  VARCHAR(10) NOT NULL,
	LONGITUD VARCHAR(10) NOT NULL,
	CONSTRAINT COD_PISTA_PK PRIMARY KEY (COD_PISTA)
);

CREATE TABLE FEDERACION(
	NOMBRE VARCHAR(40) NOT NULL,
	NUMERO INT NOT NULL,
	CONSTRAINT NOMBRE_FED_PK PRIMARY KEY (NOMBRE)
);

CREATE TABLE ESQUIADOR(
	DNI INT NOT NULL,
	NOMBRE VARCHAR(30),
	EDAD INT,
	CONSTRAINT DNI_PK PRIMARY KEY (DNI)
);

CREATE TABLE EQUIPO(
	NOMBRE VARCHAR(30) NOT NULL,
	ENTRENADOR VARCHAR(30) NOT NULL,
	N_ESQ VARCHAR(30) NOT NULL,
	CONSTRAINT NOMBRE_EQUIP_PK PRIMARY KEY (NOMBRE)
);

CREATE TABLE PRUEBA(
	COD_PRUEBA VARCHAR(12) NOT NULL,
	VENCEDOR VARCHAR(12) NOT NULL,
	TIEMPO VARCHAR(12) NOT NULL,
	CONSTRAINT COD_PRUEBA_PK PRIMARY KEY (COD_PRUEBA)
);

CREATE TABLE FECHAS(
	COD_FECHAS INT NOT NULL,
	FECHAS_PREV DATE NOT NULL,
	CONSTRAINT FECHAS_PREV PRIMARY KEY (COD_FECHAS)
);