CREATE DATABASE EJERCISIO_3
GO
USE EJERCISIO_3
GO

CREATE TABLE AUTORES(
	RUT VARCHAR(12) NOT NULL,
	AUTOR VARCHAR(35) NOT NULL,
	EDAD INT NOT NULL,
	NACIONALIDAD VARCHAR(50) NOT NULL,
	CONSTRAINT RUT_PK PRIMARY KEY (RUT)
);


CREATE TABLE SERIE(
	COD_SERIE VARCHAR(20) NOT NULL,
	RUT_AUTOR VARCHAR(12) NOT NULL,
	TITULO VARCHAR(100) NOT NULL,
	CALIFICACION INT NOT NULL,
	CONSTRAINT COD_SERIE_PK PRIMARY KEY(COD_SERIE),
	CONSTRAINT RUT_AUTOR_PK FOREIGN KEY (RUT_AUTOR) REFERENCES AUTORES(RUT) 
	
)


INSERT INTO AUTORES(RUT,AUTOR,EDAD,NACIONALIDAD)
VALUES('1-6','GEMINI',3,'CANADA');
INSERT INTO AUTORES(RUT,AUTOR,EDAD,NACIONALIDAD)
VALUES('3-9','Lucy',20,'Conti');

INSERT INTO SERIE(COD_SERIE,RUT_AUTOR,TITULO,CALIFICACION)
VALUES('INVENCIBLE-22','1-6','AMOUNG-US',2);

INSERT INTO SERIE(COD_SERIE,RUT_AUTOR,TITULO,CALIFICACION)
VALUES('LA TELA-22','3-9','STREET',2);

SELECT AUTOR,NACIONALIDAD FROM AUTORES WHERE RUT ='1-6';
SELECT AUTOR,NACIONALIDAD FROM AUTORES WHERE RUT ='3-9';

SELECT * FROM SERIE;

UPDATE AUTORES
SET AUTOR='DIEGO'
WHERE AUTOR='GEMINI';


