CREATE DATABASE EJERCISIO_2
GO
USE EJERCISIO_2
GO

CREATE TABLE PERSONA(
	RUT VARCHAR(12) NOT NULL,
	NOMBRE_PERSONA VARCHAR(60) NOT NULL,
	CONSTRAINT RUT_PK PRIMARY KEY (RUT)
);


CREATE TABLE TAREA(
	RUT_ESTUDIANTE VARCHAR(12) NOT NULL,
	ASIGNATURA VARCHAR(80) NOT NULL,
	CONSTRAINT RUT_FK FOREIGN KEY (RUT_ESTUDIANTE) REFERENCES PERSONA(RUT)
);


INSERT INTO PERSONA(RUT,NOMBRE_PERSONA) VALUES('2-9','DIEGO');
INSERT INTO TAREA(RUT_ESTUDIANTE,ASIGNATURA) VALUES('2-9','MODELAMIENTO DE DATOS');


SELECT NOMBRE_PERSONA,RUT FROM PERSONA;

