CREATE DATABASE Ejercisio_1;
GO
USE Ejercisio_1;
GO

-- 1. CREACIÓN DE TABLAS (Primero la tabla que NO tiene FK)
CREATE TABLE AUTOR(
    RUT VARCHAR(12) NOT NULL,
    NOMBRE_AUTOR VARCHAR(50) NOT NULL,
    CONSTRAINT RUT_PK PRIMARY KEY (RUT)
);

CREATE TABLE LIBROS(
    ISBN VARCHAR(10) NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    GENERO VARCHAR(20) NOT NULL,
    AUTOR_RUT VARCHAR(12) NOT NULL, -- Columna que conectará con AUTOR
    CONSTRAINT ISBN_PK PRIMARY KEY (ISBN),
    CONSTRAINT RUT_AUTOR_FK FOREIGN KEY (AUTOR_RUT) REFERENCES AUTOR(RUT)
);

GO -- Comando de SSMS para procesar los bloques anteriores

-- 2. INSERTAR DATOS (CRUD - CREATE)
-- IMPORTANTE: El RUT va entre comillas porque es VARCHAR
INSERT INTO AUTOR(RUT, NOMBRE_AUTOR) 
VALUES ('2-9', 'DIEGO SALDAÑA');

-- Al insertar el libro, DEBEMOS poner el RUT del autor que ya existe
INSERT INTO LIBROS(ISBN, TITULO, GENERO, AUTOR_RUT) 
VALUES ('1', 'Papelucho', 'Aventuras', '2-9');

INSERT INTO LIBROS(ISBN, TITULO, GENERO, AUTOR_RUT) 
VALUES ('2', 'Papelucho En la Clinica', 'Aventuras', '2-9');

GO

-- 3. ACTUALIZAR (CRUD - UPDATE)

UPDATE LIBROS
SET TITULO = 'Papelucho en Vacaciones'
WHERE ISBN = '1';

-- 4. ELIMINAR (CRUD - DELETE)

DELETE FROM LIBROS
WHERE ISBN = '2';

-- 5. SELECCIONAR (CRUD - READ)
SELECT NOMBRE_AUTOR FROM AUTOR;
SELECT GENERO FROM LIBROS;