--zona 1--
CREATE TABLE DS_ESTUDIANTES(
    RUT NUMBER,
    NOMBRE VARCHAR(50),
    EDAD NUMBER,
    DIRECCION VARCHAR(100),
    CONSTRAINT PK_RUT_DS_ESTUDIANTES PRIMARY KEY(RUT)
);

CREATE TABLE DS_CURSOS(
    COD_CURSO NUMBER,
    NOMBRE_CURSO VARCHAR(80),
    CANTIDAD_HORAS NUMBER,
    CONSTRAINT PK_COD_CURSO_DS_CURSOS PRIMARY KEY(COD_CURSO)
);

--zona 2--

CREATE TABLE DS_INSCRIPCIONES(
    RUT_ESTUDIANTE NUMBER,
    COD_CURSO NUMBER,
    FECHA_INSCRIPCION DATE,
    CONSTRAINT FK_RUT_EST_DS_INS FOREIGN KEY(RUT_ESTUDIANTE) REFERENCES  DS_ESTUDIANTES(RUT),
    CONSTRAINT FK_COD_CURS_DS_INS FOREIGN KEY(COD_CURSO) REFERENCES DS_CURSOS(COD_CURSO)
);

-- ZONA 3--
INSERT INTO DS_ESTUDIANTES(RUT,NOMBRE,EDAD,DIRECCION)
    VALUES(1,'JUAN PEREZ',21,'CALLE FALSA 123');

INSERT INTO DS_ESTUDIANTES(RUT,NOMBRE,EDAD,DIRECCION)
    VALUES(2,'MARIA LOPEZ',23,'CALLE REAL 456');


INSERT INTO DS_CURSOS(COD_CURSO, NOMBRE_CURSO, CANTIDAD_HORAS)
    VALUES(3, 'BASES DE DATOS', 80);

INSERT INTO DS_INSCRIPCIONES(RUT_ESTUDIANTE, COD_CURSO ,FECHA_INSCRIPCION)
    VALUES(1,3,TO_DATE('06/20/2025','MM/DD/YYYY'));

--ZONA 4--
SELECT *
FROM DS_ESTUDIANTES
WHERE (EDAD > 20);

SELECT *
FROM DS_CURSOS
WHERE (CANTIDAD_HORAS > 60);

SELECT *
FROM DS_INSCRIPCIONES
WHERE FECHA_INSCRIPCION > TO_DATE ('01/01/2025','DD/MM/YYYY');

--ZONA 5--
--AUN NO VEO RESTRICCIONES--
--ZONA 6--
ALTER TABLE DS_CURSOS
    ADD MODALIDAD VARCHAR(30);

ALTER TABLE DS_ESTUDIANTES
    ADD DIRECCION VARCHAR(150);

DELETE FROM DS_CURSOS
    MODALIDAD

--ZONA 7--
-- JOIN AUN NO LO INCLUEN EN MIS CLASES--

--ZONA 8--

UPDATE DS_ESTUDIANTES SET
    DIRECCION = 'NUEVA DIRECCIÓN 456'
    WHERE(DIRECCION= 'CALLE FALSA 123');

DELETE FROM DS_ESTUDIANTES
    WHERE(RUT= 2);


