/*Codigo por Diego Saldania*/

CREATE TABLE TABLA_DIEGO_CLIENTES{
    NUMERO_CLIENTES  NUMBER,
    NOMBRE_CLIENTES VARCHAR(50)
    APELLIDO1_CLIENTES VARCHAR(3),
    APELLIDO2_CLIENTES VARCHAR(30),
    DIRECCION_CLIENTES VARCHAR(80),
    SALDO NUMBER,
    CREDITO NUMBER,
    DESCUENTO NUMBER,
    CONSTRAINT PK_DS_NUMERO_CLIENTES PRIMARY KEY(NUMERO_CLIENTES)
};