--MODIFICAR TABLAS--
CREATE TABLE TABLA_DS_CLIENTES(
    NUMERO_CLIENTES  NUMBER,
    NOMBRE_CLIENTES VARCHAR(50),
    APELLIDO1_CLIENTES VARCHAR(30),
    APELLIDO2_CLIENTES VARCHAR(30),
    DIRECCION_CLIENTES VARCHAR(80),
    SALDO NUMBER,
    CREDITO NUMBER,
    DESCUENTO NUMBER,
    CONSTRAINT PK_DS_NUMERO_CLIENTES PRIMARY KEY(NUMERO_CLIENTES)
);

ALTER TABLE TABLA_DS_CLIENTES
    ADD CIUDAD VARCHAR(80);
