/*
NOMBRE_ESTUDIANTE: Diego Saldana
NOMBRE_PROFESOR: Carlos Castro Bustamante
FECHA:10/06/2025
NOMBRE_RAMO: Modelamiento de Datos
SECCION:1
*/

---------------------------CREACION DE TABLAS---------------------------------------------------------------------------
CREATE TABLE DS_AUTORES(
    CODIGO_AUTOR NUMBER,
    NOMBRE_AUTOR VARCHAR(200),
    APELLIDO1_AUTOR VARCHAR(80),
    APELLIDO2_AUTOR VARCHAR(80),
    CONSTRAINT PK_CODIGO_AUTORES_DS PRIMARY KEY(CODIGO_AUTOR)
);

CREATE TABLE DS_EDITORIALES(
    COD_EDITORIAL NUMBER,
    NOMBRE_EDITORIAL VARCHAR(200),
    CONSTRAINT PK_CODIGO_EDITORIAL_DS PRIMARY KEY(COD_EDITORIAL)
);

CREATE TABLE DS_LIBROS(
    CODIGO_LIBRO NUMBER,
    ISBN_LIBRO NUMBER,
    TITULO_LIBRO VARCHAR(300),
    NUMERO_PAGINAS_LIBRO NUMBER,
    COD_EDITORIAL NUMBER,
    CONSTRAINT PK_CODIGO_LIBRO_DS PRIMARY KEY(CODIGO_LIBRO),
    CONSTRAINT FK_COD_LIBROS FOREIGN KEY (COD_EDITORIAL) REFERENCES DS_EDITORIALES(COD_EDITORIAL)
);

CREATE TABLE DS_EJEMPLARES(
    CODIGO_EJEMPLAR NUMBER,
    CODIGO_LIBRO NUMBER,
    LOCALIZACION VARCHAR(6),
    CONSTRAINT PK_CODIGO_EJEMPLAR PRIMARY KEY(CODIGO_EJEMPLAR),
    CONSTRAINT FK_CODIGO_EJEMPLARES FOREIGN KEY (CODIGO_LIBRO) REFERENCES DS_LIBROS(CODIGO_LIBRO)
);

CREATE TABLE DS_DETALLES_PRESTAMO_EJEMPLAR(
    CODIGO_PRESTAMO NUMBER,
    CODIGO_EJEMPLAR NUMBER,
    CONSTRAINT PK_CODIGO_PRESTAMO_EJEMPLAR PRIMARY KEY(CODIGO_PRESTAMO,CODIGO_EJEMPLAR),
    CONSTRAINT FK_CODGIO_PRESTAMO FOREIGN KEY(CODIGO_PRESTAMO) REFERENCES DS_PRESTAMOS(CODIGO_PRESTAMO),
    CONSTRAINT FK_CODIGO_EJEMPLAR FOREIGN KEY(CODIGO_EJEMPLAR) REFERENCES DS_EJEMPLARES(CODIGO_EJEMPLAR)
);


CREATE TABLE DS_DETALLES_LIBRO_AUTOR(
    CODIGO_AUTOR NUMBER,
    CODIGO_LIBRO NUMBER,
    CONSTRAINT PK_DETALLE_LIBRO_DS PRIMARY KEY(CODIGO_AUTOR,CODIGO_LIBRO),
    CONSTRAINT FK_CODIGO_AUTOR_DS FOREIGN KEY (CODIGO_AUTOR) REFERENCES DS_LIBROS(CODIGO_AUTOR),
    CONSTRAINT FK_CODIGO_LIBRO_DS FOREIGN KEY (CODIGO_LIBRO) REFERENCES DS_LIBROS(CODIGO_LIBRO)
);

CREATE TABLE DS_REGION(
    COD_REGION NUMBER,
    NOMBRE_REGION VARCHAR(30),
    CONSTRAINT PK_REGION_DS PRIMARY KEY (COD_REGION)
);

CREATE TABLE DS_CIUDAD(
    COD_CIUDAD NUMBER,
    NOMBRE_CIUDAD VARCHAR(30),
    COD_REGION NUMBER,
    CONSTRAINT PK_CIUDAD_DS PRIMARY KEY (COD_CIUDAD),
    CONSTRAINT FK_COD_REGION_DS FOREIGN KEY (COD_REGION) REFERENCES DS_REGION(COD_REGION)
);

CREATE TABLE DS_USUARIOS(
    CODIGO_USUARIOS NUMBER,
    NOMBRE_USUARIOS VARCHAR(200),
    APELLIDO1_USUARIO VARCHAR(80),
    APELLIDO2_USUARIO VARCHAR(80),
    TELEFONO_USUARIO NUMBER,
    DIRECCION_USUARIO_CALLE VARCHAR(50),
    DIRECCION_USUARIOS_NUMERO NUMBER,
    COD_CIUDAD NUMBER,
    CONSTRAINT PK_CODIGO_USUARIO_DS PRIMARY KEY (CODIGO_USUARIOS),
    CONSTRAINT FK_COD_CIUDAD_DS FOREIGN KEY (COD_CIUDAD) REFERENCES DS_CIUDAD(COD_CIUDAD)
);

CREATE TABLE DS_PRESTAMOS(
    CODIGO_PRESTAMO NUMBER,
    FECHA_PRESTAMO DATE,
    FECHA_DEVOLUCION DATE,
    CODIGO_USUARIOS NUMBER,
    CONSTRAINT PK_CODIGO_PRESTAMO PRIMARY KEY (CODIGO_PRESTAMO),
    CONSTRAINT FK_CODIGO_USUARIO FOREIGN KEY (CODIGO_USUARIOS) REFERENCES DS_USUARIOS(CODIGO_USUARIOS)
);